name = "qr-code-tracking"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
BASE_URL = "https://qr.ashhill.dev"
DEFAULT_DEST = "https://google.com"

# API_KEY is a secret — set it with:
#   wrangler secret put API_KEY

[[d1_databases]]
binding = "DB"
database_name = "qr-tracking"
database_id = "307c81aa-b8b9-46ed-8df2-e0140a49ea22"

[[kv_namespaces]]
binding = "QR_CACHE"
id = "d64b1c60c679451fbcfc0866fe6c41e4"
