name = "qr-track-worker"
main = "src/index.ts"
compatibility_date = "2024-05-29"

[[d1_databases]]
binding = "DB"
database_name = "labels-db"
database_id = "4d443da1-43ee-48bc-848d-1dc2de5ec8"

[[kv_namespaces]]
binding = "GPS_KV"
id = "0686e1ae15ba48d39ca958846f3b1b22"

[vars]
DOMAIN = "https://ashhill.dev"
DEFAULT_DEST = "https://google.com"
